voter-api/config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :lists do
    resources :face_offs
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post "users/link", :to => "users#set_user_name"

  get "heartbeat", :to => "application#heartbeat"
end

voter-api/app/models/face_off.rb
class FaceOff < ApplicationRecord
  validates_presence_of :winner_id
  validates_presence_of :loser_id
  validates_presence_of :user_id
  validates_presence_of :list_id

  belongs_to :user
  belongs_to :winner, :class_name => "Option"
  belongs_to :loser, :class_name => "Option"
  belongs_to :list
end

voter-api/app/controllers/face_offs_controller.rb
class FaceOffsController < ApplicationController
  before_action :set_face_off, only: [:show, :edit, :update, :destroy]

  # GET /face_offs
  # GET /face_offs.json
  def index
    @face_offs = FaceOff.all
  end

  # GET /face_offs/1
  # GET /face_offs/1.json
  def show
  end

  # GET /face_offs/new
  def new
    @face_off = FaceOff.new
  end

  # GET /face_offs/1/edit
  def edit
  end

  # POST /face_offs
  # POST /face_offs.json
  def create
    @face_off = FaceOff.new(face_off_params)

    respond_to do |format|
      if @face_off.save
        format.json { render json: @face_off, status: :created }
      else
        format.json { render json: @face_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /face_offs/1
  # PATCH/PUT /face_offs/1.json
  def update
    respond_to do |format|
      if @face_off.update(face_off_params)
        format.html { redirect_to @face_off, notice: 'Face off was successfully updated.' }
        format.json { render :show, status: :ok, location: @face_off }
      else
        format.html { render :edit }
        format.json { render json: @face_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /face_offs/1
  # DELETE /face_offs/1.json
  def destroy
    @face_off.destroy
    respond_to do |format|
      format.html { redirect_to face_offs_url, notice: 'Face off was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_face_off
      @face_off = FaceOff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def face_off_params
      list = List.find(params[:list_id])
      params
        .require(:face_off)
        .permit(:loser_id, :winner_id)
        .merge(:user_id => current_user.id)
        .merge(:list_id => list.id)
    end
end

voter-api/app/helpers/face_offs_helper.rb
module FaceOffsHelper
end

voter-api/app/views/face_offs/_form.html.erb
<%= form_with(model: face_off, local: true) do |form| %>
  <% if face_off.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(face_off.errors.count, "error") %> prohibited this face_off from being saved:</h2>

      <ul>
      <% face_off.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :loser_id %>
    <%= form.number_field :loser_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :winner_id %>
    <%= form.number_field :winner_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

voter-api/app/views/face_offs/edit.html.erb
<h1>Editing Face Off</h1>

<%= render 'form', face_off: @face_off %>

<%= link_to 'Show', @face_off %> |
<%= link_to 'Back', face_offs_path %>

voter-api/app/views/face_offs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Face Offs</h1>

<table>
  <thead>
    <tr>
      <th>Loser</th>
      <th>User</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @face_offs.each do |face_off| %>
      <tr>
        <td><%= face_off.loser_id %></td>
        <td><%= face_off.user_id %></td>
        <td><%= face_off.winner_id %></td>
        <td><%= link_to 'Show', face_off %></td>
        <td><%= link_to 'Edit', edit_face_off_path(face_off) %></td>
        <td><%= link_to 'Destroy', face_off, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Face Off', new_face_off_path %>

voter-api/app/views/face_offs/new.html.erb
<h1>New Face Off</h1>

<%= render 'form', face_off: @face_off %>

<%= link_to 'Back', face_offs_path %>

voter-api/app/views/face_offs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loser:</strong>
  <%= @face_off.loser_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @face_off.user_id %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @face_off.winner_id %>
</p>

<%= link_to 'Edit', edit_face_off_path(@face_off) %> |
<%= link_to 'Back', face_offs_path %>