voter-api/config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :lists do
    resources :face_offs
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post "users/link", :to => "users#set_user_name"

  get "heartbeat", :to => "application#heartbeat"
end

voter-api/app/models/list.rb
class List < ApplicationRecord
  has_many :options
  validates_presence_of :name
  validates_presence_of :user_id

  def self.build_from_params(params)
    options = params.delete(:options).values
    list = List.new(params)
    options.each do |option|
      list.options.build(:label => option[:label])
    end

    list
  end

  def remaining_face_offs(user)
    face_off_id_pairs = face_offs_for_user(user).map do |face_off|
      [face_off.winner.id, face_off.loser.id].sort
    end

    # face off pairs
    #   is list of existing [winner, loser] pairs
    #   each pair of integers is sorted ascending
    #      e.g. [3, 1].sort => [1,3]

    all_possible_combinations = options.to_a.combination(2).to_a
    #   is a list of pairs of option objects
    #      e.g. [Option("tacos"), Option("Pizza")]

    all_possible_combinations.reject do |option_pair|
      option_pair_ids = option_pair.map { |option| option.id }.sort
      # option_pair_ids
      #   [1, 3]
      face_off_id_pairs.include?(option_pair_ids)
    end
  end

  def user_has_completed_voting?(user)
    option_count = options.count
    required_face_offs = (option_count * (option_count - 1)) / 2

    face_offs_for_user(user).count == required_face_offs
  end

  def rankings
    scoreboard = options.map do |option|
      {
        :option => option,
        :wins => FaceOff.where(:winner_id => option.id).count
      }
    end.sort_by { |record| record[:wins] }.reverse

    _format_rankings(scoreboard)
  end

  def face_offs_for_user(user)
    FaceOff.where(:user_id => user.id, :list_id => id)
  end

  def all_face_offs
    return @_all_face_offs if defined?(@_all_face_offs)

    @_all_face_offs = FaceOff.where(:list_id => id)

    @_all_face_offs
  end

  def all_users_who_have_completed_voting
    all_face_offs
      .map(&:user)
      .select { |user| user_has_completed_voting?(user) }
  end

  def narrative
    all_face_offs
      .sort { |a,b| a.user.id <=> b.user.id }
      .map do |face_off|
      "#{face_off.user.name} chose #{face_off.winner.label} over #{face_off.loser.label}"
    end
  end

  def narrative_for_user
    narrative
  end

  def _format_rankings(scoreboard)
    rankings = {}
    previous_wins = nil
    previous_rank = nil
    (1..options.length).each do |rank|
      row = scoreboard.shift
      if previous_wins && row[:wins] == previous_wins
        rankings[previous_rank] << row[:option].label
        rankings[previous_rank].sort! { |a,b| a.downcase <=> b.downcase }
      else
        rankings[rank] = [row[:option].label]
        previous_rank = rank
      end

      previous_wins = row[:wins]
    end

    rankings
  end

  def ranking_for_user(user)
    scoreboard = options.map do |option|
      {
        :option => option,
        :wins => FaceOff.where(
          :user_id => user.id,
          :winner_id => option.id
        ).count
      }
    end.sort_by { |record| record[:wins] }.reverse

    _format_rankings(scoreboard)
  end

  def individual_rankings
    rankings = {}
    all_users_who_have_completed_voting.each do |user|
      rankings[user.name] = ranking_for_user(user)
    end

    rankings
  end

  def completed_voting_count
    User
      .find(all_face_offs.map(&:user_id).uniq)
      .select { |user| user_has_completed_voting?(user) }
      .length
  end
end

voter-api/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List
      .build_from_params(list_params.merge(:user_id => current_user.id))

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params
        .require(:list)
        .permit(:name, :options => [:label])
    end
end

voter-api/app/helpers/lists_helper.rb
module ListsHelper
end

voter-api/app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

voter-api/app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

voter-api/app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>List Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

voter-api/app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

voter-api/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user_id %>
</p>

<p>
  Options
  <ul>
    <% @list.options.each do |option| %>
      <li><%= option.label %></li>
    <% end %>
  </ul>
</p>

<p>
  <% @list.narrative.each do |line| %>
    <li><%= line %></li>
  <% end %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>